name: htt_get_post
description: A sample command-line application.
version: 1.0.0


environment:
  sdk: ^3.0.7

dependencies:
  http: ^0.13.3
  http_retry: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
